### ISSUE TITLE
Do you aslo develop a windows driver for it?

### ISSUE THREAD

**Issue by jeditobe** [schlae/snark-barker#3]
Do you aslo develop a windows driver for it?

ReactOS project needs your knowledge and experience  https://github.com/reactos/reactos

**Comment by volkertb** [comment]
Since this card is intended to be a 100% compatible replica of the original SB 1.0 card, the existing drivers available for that card should work this card without any modifications. Or do you mean drivers for modern Windows versions? That might prove problematic, since (as far as I have understood), newer Windows versions no longer provide support for ISA-based expansion cards. But I'm sure someone else here can correct me if I'm wrong or misunderstood the question.

**Comment by NukemD** [comment]
The Sound Blaster 1.0 was released in 1989, about a year before the first widely used version of Windows was released (3.0). It was never designed with Windows support in mind, it was purely a DOS sound card.

It doesn't make sense to write a driver for an ancient 8 bit ISA sound card for an OS that would be crippled by it. ReactOS targets Windows XP compatibility, and machines of the time period had already pretty much eliminated ISA slots. The few that did have ISA often had limitations that would break support for the card, like lacking DMA support.

Even assuming you had a weird setup to use the card, you'd have to write special software to take advantage of the card. It was primarily designed for FM synthesis by utilizing a YM3812 and could only sample monaural PCM audio at 8 bit 23 kHz.
