### ISSUE TITLE
Questions about 80C51/DSP

### ISSUE THREAD

**Issue by elosha** [schlae/snark-barker#6]
I'm totally looking forward to build a Snark Barker. I am very curious and have a few questions about these sentences:

> There are two ways to get a programmed 80C51 chip for the Snark Barker. One is to purchase a SB 2.0 DSP chip from China and put it in a 44-PLCC to 40-DIP adapter. This works fine and provides the largest feature set.

1. Does 'largest feature set' mean SB 2.0 instead of SB 1.0 specifications; and if so, which features of the Snark Barker will change? Or is the 80C51 firmware missing DSP features?

> Another option is to buy a blank Atmel 89S51 (as listed in the BOM) and program it with this HEX file.

2. Will any 8051 or 80C51 with 8KB of ROM work, or do we require any of the newer Atmel features?
3. Was the original DSP from Creative based on a 80C51, too?

Thank you for answering and your impressive work, maybe you can even add the info to [README.md](https://github.com/schlae/snark-barker/blob/master/README.md).

**Comment by schlae** [comment]
DSP 2.0 gives you auto-init DMA and a high speed playback mode. It's also the original DSP so it is exactly compatible. The other image in the repo is from a knockoff and, although it too supports auto-init DMA and high speed playback, may not be 100% compatible. I have no way to verify that it is.

No new Atmel features are required, so you could use an 80C51 (technically an 87C51 since the 80C51 is mask-ROM only) from any number of different vendors. The Atmel part is the one that I tested with.

**Comment by elosha** [comment]
Great, thank you for your quick reply. I read about auto-init DMA (crackle-free playback) und high-speed playback (44.1KHz) now and they seem like worthy improvements to have. But that knockoff image is missing in the repo.

Regarding compatibility of the knockoff, are there known problems or do you simply not want to guarantee the same level of compability?

Would it be possible to simply dump an original DSP 2.0?

**Comment by schlae** [comment]
The image is [here](https://github.com/schlae/snark-barker/blob/master/firmware/sb.hex).

**Comment by elosha** [comment]
Thanks, I thought this was the 1.0 DSP featureset image.
